### ISSUE TITLE
Does not work with Insiders version of VSCode

### ISSUE THREAD

**Issue by marcsandusky** [microhobby/linuxkerneldev#2]
The scripts all refer to the executable "code". The executable for the Insiders track of VSCode is "code-insiders". Hand editing the scripts where they are installed to call the correct executable restores functionality to the extension.

**Comment by microhobby** [comment]
@marcsandusky thanks to pointing it.

**Comment by microhobby** [comment]
@marcsandusky the fix is release on the last update: https://marketplace.visualstudio.com/items?itemName=microhobby.linuxkerneldev

Let me know if this works for you, so we can close this issue.

**Comment by marcsandusky** [comment]
This seems to work correctly now.
